name: Build

on:
  push:
    branches: [main, next]
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "docs/**"

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  CARGO_PROFILE_DEV_DEBUG: 0
  RUST_CACHE_KEY: rust-cache-2026.02.18

jobs:
  build:
    name: Build Client and CLI
    runs-on: warp-ubuntu-latest-x64-8x
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Cleanup large tools for build space
        uses: ./.github/actions/cleanup-runner
      - name: Install Rust toolchain
        run: rustup update --no-self-update
      - name: Add Rust Cache
        uses: WarpBuilds/rust-cache@9d0cc3090d9c87de74ea67617b246e978735b1a1 # v2.9.1
        with:
          shared-key: rust-release
          prefix-key: ${{ env.RUST_CACHE_KEY }}
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: make - build
        run: make build
